server:
  port: 9000

spring:
  redis:
    host: localhost
    jedis:
      pool:
        max-active: -1
        max-wait: 3000ms

    timeout: 3000ms

  datasource:
    dynamic:
      p6spy: true
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/news-boot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis-plus:
  mapper-locations: classpath*:com/system/modules/**/xml/*.xml

#enable swagger
swagger:
  enable: true

#showSql
logging:
  level:
    root : info
    com.system.modules.**.mapper: debug

