server:
  port: 9000

spring:
  redis:
    host: localhost
    jedis:
      pool:
        max-active: -1
        max-wait: 3000ms

    timeout: 3000ms

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/news-boot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mvc:
  datasource:
    dynamic:
      p6spy: true

mybatis-plus:
  mapper-locations: classpath:com/boot/module/system/modules/**/xml/*Mapper.xml

#enable swagger
swagger:
  enable: true

#showSql
logging:
  level:
    com:
      example:
        mapper : debug


